import "./globals.css";
import Navbar from "@/Components/Navbar";
import { Inter, Roboto } from "next/font/google";

// Define your fonts
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-auto max-w-7xl">
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
